services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=NoteDB
      - POSTGRES_USER=${DATABASES_USER}
      - POSTGRES_PASSWORD=${DATABASES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: sh -c "python NoteTZ/manage.py migrate && python NoteTZ/manage.py runserver 0.0.0.0:8000"

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=NoteDB
      - DB_USER=${DATABASES_USER}
      - DB_PASSWORD=${DATABASES_PASSWORD}
      - DB_HOST=db 
      - DB_PORT=5432
    
    depends_on:
      - db

volumes:
  postgres_data: